Created Active Users Component
harled/matey pull request #2
Opened 2022-03-11 19:06 UTC by suvasan19

2022-03-13 01:45 UTC, krsyoung commented
@suvasan19 I think we have an initial version here. Definitely need some polishing ... take a look at the code changes and let me know what you think.

We should probably include the following in the README as well:

1. Dependency (soft) on Bootstrap 5.x
2. Current requirement to load the gem directly from our GitHub (branch can vary)
3. Need to investigate slots (@jonathanloos can probably help) for custom HTML
4. Need to compare this to the webcomponents version per @Technickel-Dev

2022-03-15 04:39 UTC, Technickel-Dev requested changes
Just two small fixes in the HTML to avoid bugs in the future

2022-03-15 04:39 UTC, Technickel-Dev commented on app/components/matey/active_users_component.html.erb
> +        <h5 class="card-text my-2"><strong> Active Users </strong> since <%= time_ago_in_words(@time_window.ago) %> ago</h6>
Start as h5, but close h6

2022-03-15 04:39 UTC, Technickel-Dev commented on app/components/matey/active_users_component.html.erb
> +          <h1 class="card-title"><%= @current_period.to_s %></h5>
Start as h1 but closes h5

2022-03-16 00:22 UTC, krsyoung commented on app/components/matey/active_users_component.html.erb
> +<div class="card widget-flat shadow-sm">
@suvasan19 what's going on with the classes here? If we're introducing some weird classes?

What is "widget-flat"?

2022-03-16 00:23 UTC, krsyoung commented on app/components/matey/active_users_component.html.erb
> +    <div id="first col" class="col">
I'm not sure if I added this, but what is the purpose of the ids? I'm sure we don't need them .. (it won't work if we have multiple cards on the same page as ids must be unique).

2022-03-16 00:23 UTC, krsyoung commented on app/components/matey/active_users_component.html.erb
> +      <div class="col">
Is this `col` in the `row`? Seems like it is outside?

2022-03-16 00:24 UTC, krsyoung commented
@suvasan19 I've found a number of issues with the HTML, which I'm not sure if there is a reason for (or if I was the one that added them!). Let me know if they are valid for some reason, or let's clean them up.

2022-03-16 21:29 UTC, merged